#!/usr/bin/perl
#
# $Id: old-port-utils.pm,v 1.3 2001-12-22 04:30:40 dan Exp $
#
# Copyright (c) 200 DVL Software
#

package ports;
require	Exporter;

use strict;

use File::PathConvert;

my $PORTSBASEDIR = "/usr/ports";
my $SCRIPTDIR    = "/home/freshports.org/scripts";

@ISA	= qw(Exporter);
@EXPORT	= qw(PortUpdate ExtractCategoryFromDirectory GetDescrAndHomePage ReadFile PackageExists RefreshPort SendWatchNotice FilesWhichPromptRefresh RefreshOnePort CreateDailySummary GetNeedsRefreshForNewPort GetPortCategory GetPortID CreateCategory SendWatchNoticePersonal);

sub SendWatchNotice($) {

  my $Bcc = shift;

   open(SENDMAIL, "|/usr/sbin/sendmail -oi -t")
                    or die "Can't fork for sendmail: $!\n";

print SENDMAIL <<"EOF";
From: FreshPorts watch daemon <freshports-watch\@freshports.org>
To: freshports-watch\@freshports.org
Bcc: $Bcc
Subject: FreshPorts watch list notification
zThis message was generated by the FreshPorts Watch Daemon.  Something 
on your watch list has changed.  Please refer to 
http://freshports.org/watch.php3 for details.

Cheers and thanks for your support.

--

You are receiving this message as part of the service you joined at
http://freshports.org/ but if you no longer wish to recieve such messages,
please go to http://freshports.org/customize.php3 and disable mailings.

If a problem occurs, please send details, including the email address in
question, to postmaster\@freshports.org.
EOF

   close(SENDMAIL)     or warn "sendmail didn't close nicely";

}

sub SendWatchNoticePersonal($;$;$) {

  my $To            = shift;
  my $FrequencyLong = shift;
  my $Body          = shift;

   open(SENDMAIL, "|/usr/sbin/sendmail -oi -t")
                    or die "Can't fork for sendmail: $!\n";

print SENDMAIL <<"EOF";
From: FreshPorts watch daemon <freshports-watch\@freshports.org>
To: $To
Subject: FreshPorts $FrequencyLong notification

This message was generated by the FreshPorts Watch Daemon and highlights
your selected ports which have changed since the last notification.  You
have chosen to recieve these notices on a $FrequencyLong basis.

$Body

Please refer to http://freshports.org/watch.php3 for details.

Cheers and thanks for your support.

--

You are receiving this message as part of the service you joined at
http://freshports.org/ but if you no longer wish to recieve such messages,
please go to http://freshports.org/customize.php3 and disable mailings.

If a problem occurs, please send details, including the email address in
question, to postmaster\@freshports.org.
EOF

   close(SENDMAIL)     or warn "sendmail didn't close nicely";

}

sub PortUpdate($;$;$;$;$;$;$;$;$;$;$;$;$;$;$;$;$;$;$) {
   my $name             = shift;
   my $portname         = shift;
   my $category         = shift;
   my $descrfile        = shift;
   my $categories       = shift;
   my $portversion      = shift;
   my $commentfile      = shift;
   my $maintainer       = shift;
   my $extractsuffix    = shift;
   my $mastersites      = shift;
   my $builddepends     = shift;
   my $rundepends       = shift;
   my $shortdescription = shift;
   my $longdescription  = shift;
   my $homepage         = shift;
   my $packageexists    = shift;
   my $forbidden	= shift;
   my $broken		= shift;
   my $dbh              = shift;

   my $result = 0;

   # do some tidy up to add slashes

   #  these bits might have \'s.
   $longdescription  =~ s/\\/\\\\/g;
   $shortdescription =~ s/\\/\\\\/g;
   $forbidden        =~ s/\\/\\\\/g;
   $broken           =~ s/\\/\\\\/g;

   #  these bits might have quotes.
   $longdescription  =~ s/\'/\\'/g;
   $shortdescription =~ s/\'/\\'/g;
   $forbidden        =~ s/\'/\\'/g;
   $broken           =~ s/\'/\\'/g;

   if ($name ne $portname) {
      print "*************** port ('$name') differs from portname('$portname')\n";
   }

   print " 0 $name\n";
   print " 1 $portname\n";
   print " a $category\n";
   print " 2 $descrfile\n";
   print " 3 $categories\n";
   print " 4 $portversion\n";
   print " 5 $commentfile\n";
   print " 6 $maintainer\n";
   print " 7 $extractsuffix\n";
   print " 8 $mastersites\n";
   print " 9 $builddepends\n";
   print "10 $rundepends\n";
   print "11 $shortdescription\n";
   print "12 $longdescription\n";
   print "13 ";
   if (defined($homepage)) {
      print "$homepage";                 # this may be an unitialized value
   }
   print "\n";
   print "14 $packageexists\n";

   # this asks for user input
   #<STDIN>;

   #return;

   my $categoryid = GetPortCategory($category, $dbh);
   if (!$categoryid) {
      print "ERROR *** could not find category for $category\n";
      return -2;
   }

   # update the port, creating it if necessary

   my $sql = "select id from ports where name = '$name' and primary_category_id = $categoryid";
   print "sql = ", $sql, "\n";
   my $sth = $dbh->prepare($sql);

   $sth->execute ||
      die "Could not execute SQL statement ... maybe invalid?";

   my @row=$sth->fetchrow_array;

   if (@row) {
      print "something found\n";
   } else {
      print "nothing found\n";
   }

   # Get the short description (and escape them)
   # Get the long description (and escape them)
   # get homepage
   # get package exists

   print "port ID found = ", $row[0], "\n";
   if (!@row) {
      # no such port.  create it.
      $sql = "insert into ports (name,                                                                    \
              primary_category_id, system, version, date_created,                                         \
              short_description, long_description, maintainer, categories,                                \
              date_last_refreshed, needs_refresh, homepage, master_sites, extract_suffix, package_exists, \
              status, depends_run, depends_build, forbidden, broken) values (";

      $sql .= "'$name', $categoryid ,                                                     \
              'FreeBSD', '$portversion', current_timestamp, '$shortdescription',          \ 
              '$longdescription', '$maintainer', '$categories', current_timestamp, 'N', ";

      if (defined($homepage)) {
         $sql .= "'$homepage', ";
      } else {
         $sql .= "NULL, ";
      }

      $sql .= "'$mastersites', '$extractsuffix', '$packageexists', 'A',       \
               '$rundepends', '$builddepends', '$forbidden', '$broken')";

      print "$sql\n";

      $sth = $dbh->prepare($sql) || 
         die "Could not insert statement ... maybe invalid? " . mysql_error() ;

      $sth->execute ||
         die "Could not insert statement ... maybe invalid? " . mysql_error();
   } else {
      # update the time on the port
      $sql = "update ports set \ 
              version = '$portversion', short_description = \
              '$shortdescription', long_description = '$longdescription', maintainer = \
              '$maintainer', categories = '$categories', date_last_refreshed = \
              current_timestamp, ";

      if (defined($homepage)) {
         $sql .= "homepage = '$homepage',";
      } else {
         $sql .= "homepage = NULL,";
      }

#
# This may be a source of possible problems.  We may have to start locking the table before doing this.
# otherwise one update may clear the needs_refresh flags set by another update.
# Not a really serious problem, but a definite annoyance.
#
      $sql .= " master_sites = '$mastersites', \
                extract_suffix = '$extractsuffix', package_exists = '$packageexists', \
                needs_refresh = 0, depends_run = '$rundepends', depends_build = '$builddepends', \
                forbidden = '$forbidden', broken = '$broken' \
                where id = $row[0]";

      print "$sql\n";

      $sth = $dbh->prepare($sql) || die "Could not prepare ... maybe invalid?" . mysql_error();

      $sth->execute ||
         die "Could not execute update statement ... maybe invalid?";
   }

   return $result;
}


sub RefreshPortNoChecking($;$;$;$;$) {

   my $DirectoryOfMakeFile = shift;
   my $Category            = shift;
   my $Port                = shift;
   my $NameOfMakefile      = shift;
   my $dbh                 = shift;


   # a return of zero indicates success.
   my $result = 0;

   #
   # if we don't change the working dir, stuff like descrpath will not
   # contain /usr/ports/...etc.  It will look more like this:
   #     /usr/home/dan/walkports/
   # That's because DESCR is defined as .{CURDIR}/etc more or less
   #


   #
   # create this directory to catch errors
   # such as the pre-everything having only one ':'
   #
}

sub RefreshPort($;$;$) {

   my $dirname = shift;
   my $port    = shift;
   my $dbh     = shift;

   #
   # a return of zero indicates success
   #
   my $result = 0;

   print "... now checking $dirname/$port .... ";
   if (-d "$dirname/$port") {
      #
      # at one time, $IGNOREDPORTS contained . and .. but that caused
      # problems with port names which contained a '.'
      # hence, this solution.  Also, pkg causes similar problems
      # as the port pkg_remove would match that
      # my $IGNOREDPORTS = "pkg|CVS|apache13-php3-fp-modssl|Makefile";
      if ($port eq "." || $port eq ".." || $port eq "pkg" || $port eq "CVS" || $port eq $FILE_MAKEFILE) {
         print "port is in the IGNORE list... skipping\n";
      } else {
         if (!-e "$dirname/$port/$FILE_MAKEFILE") {
            print " ...$FILE_MAKEFILE does not exist (port must be in Attic)\n";
         } else {
            print "...now looking at $dirname/$port/$FILE_MAKEFILE\n";

            my $category = ExtractCategoryFromDirectory($dirname);

            $result = RefreshPortNoChecking("$dirname/$port", $category, $port, $FILE_MAKEFILE, $dbh);

         }  # else yes, the Makefile does exist.
      }
   } else {
      print "directory does not exist... skipping\n";
      $result = -1;
   }

   return $result;
}

}


sub CreateDailySummary($;$) {

   my $PathToUse       = "/usr/local/etc/freshports/archives";  # must NOT include a trailing /
   my @myrow;
   my $CommitDateStart = shift;
   my $dbh             = shift;

   my $sql = "select ports.id, ports.name, ports.version " .
             "from ports, change_log_port, change_log ".
             "where ports.id                      = change_log_port.port_id ".
             "  and change_log_port.change_log_id = change_log.id ".
             "  and change_log.commit_date between '$CommitDateStart' and Date_Add('$CommitDateStart', INTERVAL 1 DAY) " .
             "order by change_log.commit_date desc";

   my $sth = $dbh->prepare($sql);

   $sth->execute ||
        die "Could not execute SQL statement\n--$sql--\n... maybe invalid?";


   print "$sql\n";

#   if ($sth->num_rows) {
#      print "$sth->num_rows rows in that result\n";
#   }

#   print "press enter to continue"; <STDIN>;

   umask(02);
   # create the output file name gradually, ensuring the directories exist

   my $OutputFile = $PathToUse . "/" . substr($CommitDateStart, 0, 4);

   if (-d $OutputFile) {
      print "'$OutputFile' exists\n";
   } else {
      print "'$OutputFile' does not exist\n";
      print "   trying to mkdir '$OutputFile'\n";
      if (mkdir $OutputFile, 0775) {
      } else {
         print "Could not create directory $OutputFile\n";
         return 1;
      }
   }

   $OutputFile .= "/" . substr($CommitDateStart, 5, 2);
   if (-d $OutputFile) {
      print "'$OutputFile' exists\n";
   } else {
      print "   trying to mkdir '$OutputFile'\n";
      if (mkdir $OutputFile, 0775) {
      } else {
         print "Could not create directory $OutputFile\n";
         return 2;
      }
   }

   $OutputFile .= "/" .  substr($CommitDateStart, 8, 2) . ".inc";
   print "   trying to open '$OutputFile'\n";
   open FILE, ">$OutputFile"  || die "Could not open $OutputFile";
   
   if (*FILE) {
      print "that file was opened.  now writing output\n";
      my $count =0;
      while (@myrow = $sth->fetchrow_array) {
         print FILE '<a href="port-description.php3?port=';
         print FILE $myrow[0] . '"><font size="-1">' . $myrow[1] . " ";
         print FILE $myrow[2] . "</font></a><br>\n";     
         $count++;
      }
             
      print "i wrote out $count records\n";

      close FILE;
   } else {
      print "could not open $OutputFile\n";
      return 3;
   }
   
   return 0;
}

1;